import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import { HttpClient } from '@angular/common/http';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { EffectsModule } from '@ngrx/effects';
import { StoreModule } from '@ngrx/store';
import { NgxMaskDirective, NgxMaskPipe, provideNgxMask } from 'ngx-mask';

import { NzSpinModule } from 'ng-zorro-antd/spin';
import { NzPopoverModule } from 'ng-zorro-antd/popover';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzDropDownModule } from 'ng-zorro-antd/dropdown';
import { NzRadioModule } from 'ng-zorro-antd/radio';
import { NzTreeModule } from 'ng-zorro-antd/tree';
import { NzTransferModule } from 'ng-zorro-antd/transfer';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzPopconfirmModule } from 'ng-zorro-antd/popconfirm';
import { NzUploadModule } from 'ng-zorro-antd/upload';
import { NzTabsModule } from 'ng-zorro-antd/tabs';
import { NzCalendarModule } from 'ng-zorro-antd/calendar';
import { NzDatePickerModule } from 'ng-zorro-antd/date-picker';
import { NzToolTipModule } from 'ng-zorro-antd/tooltip';
import { NzSliderModule } from 'ng-zorro-antd/slider';
import { NzCheckboxModule } from 'ng-zorro-antd/checkbox';
import { NzTreeSelectModule } from 'ng-zorro-antd/tree-select';
import { NzInputNumberModule } from 'ng-zorro-antd/input-number';

import { SwiperDirective } from '@directive';
import { AdminLayout } from '@layouts';
import { FormatCurrencyPipe, FormatDatePipe, FullTextSearchPipe } from '@pipes';
import {
  GButtonModule,
  GDatatableModule,
  GFormModule,
  GModalFormModule,
  GModalModule,
  GPaginationModule,
  GUploadModule,
} from '@core';
import {
  DashboardComponent,
  PostsComponent,
  EditCategoryPostComponent,
  EditPostComponent,
  NavigationComponent,
  ParameterComponent,
  DataComponent,
  EditDataComponent,
  EditTypeDataComponent,
  CodeTypesComponent,
  EditCodeTypeComponent,
  EditProfileComponent,
  AccountComponent,
  EditAccountComponent,
  PasswordAccountComponent,
  DetailAccountComponent,
  AddressComponent,
  ClinicsComponent,
  EditClinicComponent,
  DetailClinicComponent,
  EscrowMoneyComponent,
  EscrowListComponent,
  DetailEscrowListComponent,
  EscrowWithdrawalListComponent,
  DetailEscrowWithdrawalListComponent,
  ModalReasonsEscrowListComponent,
  ModalReasonsEscrowWithdrawalListComponent,
  MedicalProcedureComponent,
  EditProvinceCommissionComponent,
  EditMedicalProcedureComponent,
  DetailMedicalProcedureComponent,
  ProfileFarmerComponent,
  EditProfileFarmerComponent,
  DetailProfileFarmerComponent,
  WalletDepositsComponent,
  WalletListsComponent,
  WalletSmsComponent,
  WalletWithdrawalsComponent,
  DetailWalletListComponent,
  DetailWalletWithdrawalsComponent,
  DetailWalletDepositsComponent,
  CustomerManagementComponent,
  OrderComponent,
  DetailOrderComponent,
  DetailProposalOrderComponent,
  DetailTreamentDiariesComponent,
  ClaimsOrderComponent,
  DetailClaimsComponent,
  ChangeFarmerComponent,
  PaymentContentComponent,
  PaymentHistoryComponent,
  PaymentSettingsComponent,
  FeedbackComponent,
  DetailFeedbackComponent,
  ClinicFeedbackComponent,
  FarmerFeedbackComponent,
} from '@pages';

import {
  POSTS_FEATURE_KEY,
  PostsEffects,
  postsReducer,
  POST_CATEGORIES_FEATURE_KEY,
  PostCategoriesEffects,
  postCategoriesReducer,
  DATAS_FEATURE_KEY,
  DatasEffects,
  datasReducer,
  DATA_TYPES_FEATURE_KEY,
  TYPES_CODE_TYPE_FEATURE_KEY,
  DataTypesEffects,
  dataTypesReducer,
  NAVIGATION_FEATURE_KEY,
  NavigationEffects,
  navigationReducer,
  UPLOAD_FEATURE_KEY,
  UploadEffects,
  uploadReducer,
  ADDRESS_FEATURE_KEY,
  AddressEffects,
  addressReducer,
  ROLE_FEATURE_KEY,
  RoleEffects,
  roleReducer,
  CODE_TYPES_FEATURE_KEY,
  CodeTypesEffects,
  codeTypesReducer,
  USER_FEATURE_KEY,
  UserEffects,
  userReducer,
  typesCodeTypeReducer,
  TypesCodeTypeEffects,
  CodeTypeEffects,
  codeTypeReducer,
  CODE_TYPE_FEATURE_KEY,
  PARAMETERS_FEATURE_KEY,
  parametersReducer,
  ParametersEffects,
  CLINICS_FEATURE_KEY,
  clinicsReducer,
  ClinicsEffects,
  EscrowListEffects,
  ESCROW_LIST_FEATURE_KEY,
  escrowListReducer,
  EscrowWithdrawalListEffects,
  ESCROW_WITHDRAWAL_LIST_FEATURE_KEY,
  escrowWithdrawalListReducer,
  MedicalProcedureEffects,
  MEDICAL_PROCEDURE_FEATURE_KEY,
  medicalProcedureReducer,
  PROFILE_FARMER_FEATURE_KEY,
  profileFarmerReducer,
  ProfileFarmerEffects,
  WalletListEffects,
  WALLET_LIST_FEATURE_KEY,
  walletListReducer,
  WALLET_DEPOSITS_FEATURE_KEY,
  walletDepositsReducer,
  WalletDepositsEffects,
  WalletSmsEffects,
  WALLET_SMS_FEATURE_KEY,
  walletSmsReducer,
  WalletWithDrawalsEffects,
  WALLET_WITH_DRAWALS_FEATURE_KEY,
  walletWithDrawalsReducer,
  CUSTOMER_MANAGEMENT_FUTURE_KEY,
  CustomerEffects,
  customerReducer,
  ORDER_FEATURE_KEY,
  ordersReducer,
  OrdersEffects,
} from '@store';
import { environment } from '@src/environments/environment';
import { AdminRouting } from './admin.routing';

@NgModule({
  declarations: [
    DashboardComponent,
    AdminLayout,
    SwiperDirective,
    FormatDatePipe,
    FormatCurrencyPipe,
    FullTextSearchPipe,
    NavigationComponent,
    ParameterComponent,
    PostsComponent,
    DataComponent,
    EditCategoryPostComponent,
    EditPostComponent,
    EditDataComponent,
    EditTypeDataComponent,
    EditCodeTypeComponent,
    CodeTypesComponent,
    EditProfileComponent,
    EditCodeTypeComponent,
    CodeTypesComponent,
    AccountComponent,
    EditAccountComponent,
    PasswordAccountComponent,
    DetailAccountComponent,
    AddressComponent,
    ClinicsComponent,
    EditClinicComponent,
    DetailClinicComponent,
    EscrowMoneyComponent,
    EscrowListComponent,
    DetailEscrowListComponent,
    EscrowWithdrawalListComponent,
    DetailEscrowWithdrawalListComponent,
    ModalReasonsEscrowListComponent,
    ModalReasonsEscrowWithdrawalListComponent,
    MedicalProcedureComponent,
    EditProvinceCommissionComponent,
    EditMedicalProcedureComponent,
    DetailMedicalProcedureComponent,
    ProfileFarmerComponent,
    EditProfileFarmerComponent,
    DetailProfileFarmerComponent,
    WalletDepositsComponent,
    WalletListsComponent,
    WalletSmsComponent,
    WalletWithdrawalsComponent,
    DetailWalletListComponent,
    DetailWalletWithdrawalsComponent,
    DetailWalletDepositsComponent,
    CustomerManagementComponent,
    OrderComponent,
    DetailOrderComponent,
    DetailProposalOrderComponent,
    DetailTreamentDiariesComponent,
    ClaimsOrderComponent,
    DetailClaimsComponent,
    ChangeFarmerComponent,
    PaymentContentComponent,
    PaymentHistoryComponent,
    PaymentSettingsComponent,
    FeedbackComponent,
    DetailFeedbackComponent,
    ClinicFeedbackComponent,
    FarmerFeedbackComponent,
  ],
  imports: [
    CommonModule,
    AdminRouting,
    FormsModule,
    ReactiveFormsModule,
    GButtonModule,
    GDatatableModule,
    GFormModule,
    GPaginationModule,
    GUploadModule,
    GModalModule,
    GModalFormModule,
    NgxMaskDirective,
    NgxMaskPipe,
    TranslateModule.forRoot({
      defaultLanguage: localStorage.getItem('ng-language') || environment.language,
      loader: {
        provide: TranslateLoader,
        useFactory: function HttpLoaderFactory(http: HttpClient): TranslateHttpLoader {
          return new TranslateHttpLoader(http, 'assets/translations/');
        },
        deps: [HttpClient],
      },
    }),
    NzSpinModule,
    NzPopoverModule,
    NzSelectModule,
    NzDropDownModule,
    NzRadioModule,
    NzTreeModule,
    NzTransferModule,
    NzFormModule,
    NzPopconfirmModule,
    NzDatePickerModule,
    NzUploadModule,
    NzTabsModule,
    NzCalendarModule,
    NzToolTipModule,
    NzCheckboxModule,
    NzTreeSelectModule,
    NzSliderModule,
    NzInputNumberModule,
    EffectsModule.forFeature([
      PostsEffects,
      PostCategoriesEffects,
      DatasEffects,
      DataTypesEffects,
      NavigationEffects,
      UploadEffects,
      AddressEffects,
      CodeTypesEffects,
      RoleEffects,
      UserEffects,
      TypesCodeTypeEffects,
      CodeTypesEffects,
      CodeTypeEffects,
      ParametersEffects,
      ClinicsEffects,
      EscrowListEffects,
      EscrowWithdrawalListEffects,
      MedicalProcedureEffects,
      ProfileFarmerEffects,
      WalletListEffects,
      WalletDepositsEffects,
      WalletSmsEffects,
      WalletWithDrawalsEffects,
      CustomerEffects,
      OrdersEffects,
    ]),
    StoreModule.forFeature(POSTS_FEATURE_KEY, postsReducer),
    StoreModule.forFeature(POST_CATEGORIES_FEATURE_KEY, postCategoriesReducer),
    StoreModule.forFeature(DATAS_FEATURE_KEY, datasReducer),
    StoreModule.forFeature(DATA_TYPES_FEATURE_KEY, dataTypesReducer),
    StoreModule.forFeature(NAVIGATION_FEATURE_KEY, navigationReducer),
    StoreModule.forFeature(UPLOAD_FEATURE_KEY, uploadReducer),
    StoreModule.forFeature(ADDRESS_FEATURE_KEY, addressReducer),
    StoreModule.forFeature(CODE_TYPES_FEATURE_KEY, codeTypesReducer),
    StoreModule.forFeature(ROLE_FEATURE_KEY, roleReducer),
    StoreModule.forFeature(USER_FEATURE_KEY, userReducer),
    StoreModule.forFeature(TYPES_CODE_TYPE_FEATURE_KEY, typesCodeTypeReducer),
    StoreModule.forFeature(CODE_TYPE_FEATURE_KEY, codeTypeReducer),
    StoreModule.forFeature(PARAMETERS_FEATURE_KEY, parametersReducer),
    StoreModule.forFeature(CLINICS_FEATURE_KEY, clinicsReducer),
    StoreModule.forFeature(ESCROW_LIST_FEATURE_KEY, escrowListReducer),
    StoreModule.forFeature(ESCROW_WITHDRAWAL_LIST_FEATURE_KEY, escrowWithdrawalListReducer),
    StoreModule.forFeature(MEDICAL_PROCEDURE_FEATURE_KEY, medicalProcedureReducer),
    StoreModule.forFeature(PROFILE_FARMER_FEATURE_KEY, profileFarmerReducer),
    StoreModule.forFeature(WALLET_LIST_FEATURE_KEY, walletListReducer),
    StoreModule.forFeature(WALLET_DEPOSITS_FEATURE_KEY, walletDepositsReducer),
    StoreModule.forFeature(WALLET_SMS_FEATURE_KEY, walletSmsReducer),
    StoreModule.forFeature(WALLET_WITH_DRAWALS_FEATURE_KEY, walletWithDrawalsReducer),
    StoreModule.forFeature(CUSTOMER_MANAGEMENT_FUTURE_KEY, customerReducer),
    StoreModule.forFeature(ORDER_FEATURE_KEY, ordersReducer),
  ],
  providers: [provideNgxMask()],
})
export class AdminModule {}
